//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidPay.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidPay.Domain.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card number must have 15 digits.
        /// </summary>
        public static string RP001 {
            get {
                return ResourceManager.GetString("RP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card number is already registered.
        /// </summary>
        public static string RP002 {
            get {
                return ResourceManager.GetString("RP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card balance must be greater than 100 USD.
        /// </summary>
        public static string RP003 {
            get {
                return ResourceManager.GetString("RP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card number does not exists.
        /// </summary>
        public static string RP004 {
            get {
                return ResourceManager.GetString("RP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount to pay must be greater than 0.
        /// </summary>
        public static string RP005 {
            get {
                return ResourceManager.GetString("RP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is wrong.
        /// </summary>
        public static string RP006 {
            get {
                return ResourceManager.GetString("RP006", resourceCulture);
            }
        }
    }
}
